### ISSUE TITLE
Ensure recent Appts date searching changes are reflected in swagger defs for 1.x

### ISSUE THREAD

**Issue by jonnyry** [nhsconnect/gpconnect-swagger#3]
E.g. no time element

**Comment by lucywilcock** [comment]
This has been completed. The start parameter requires two parameters (one ge date and one le date). These are now the default in the swagger UI. The demonstrator does not allow dates in the past so these will have to be updated as necessary. Or the user can just change them as need be.

This has been completed in the 1.0.0 release branch and the master branch.
