### ISSUE TITLE
Add structured swagger definitions (1.2.0)

### ISSUE THREAD

**Issue by jonnyry** [nhsconnect/gpconnect-swagger#4]

**Comment by lucywilcock** [comment]
I have added the structure record definitions into swagger. I have included both allergies and medications and both the part parameters as standard for the example. I have not included the date parameter for the medications as the dates will change. This can be added in by the user if they so wish or added to swagger easily if it is needed.

As this is not part of 1.0.0/1.1.0 and as structured record is not yet available on the demonstrator I have not added the changes into master or the 1.0.0 release branch. The changes can be found in a new 1.2.0 release branch. 

This can be merged with master when the demonstrator is updated or as required.
