### ISSUE TITLE
Uplift swagger for changes to structured

### ISSUE THREAD

**Issue by james-answer** [nhsconnect/gpconnect-swagger#6]
The structured requests have been update so that the part parameters are mandatory. We need to update the swagger definition so that it includes the changes that have been made to the specification since the last update of the definitions.

**Comment by lucywilcock** [comment]
The parameters for the structured request are added in as part of the body. This is different to other places where additional parameters are part of url (query params). The part parameters were already part of the body request, defaulted to true. I don't think any change needs to be made.
